### ISSUE TITLE
Support ctrl+d

### ISSUE THREAD

**Issue by rainu** [rainu/jsimpleshell#82]
Support the &lt;ctrl&gt;+&lt;d&gt; combination. If u enter this combo you will get an NullPointerException:

de.raysha.lib.jsimpleshell.exception.CLIException: java.lang.NullPointerException
	at de.raysha.lib.jsimpleshell.ShellCommand.invoke(ShellCommand.java:77)
	at de.raysha.lib.jsimpleshell.Shell.processCommand(Shell.java:775)
	at de.raysha.lib.jsimpleshell.Shell.processLine(Shell.java:748)
	at de.raysha.lib.jsimpleshell.Shell.processLine(Shell.java:704)
	at de.raysha.lib.jsimpleshell.Shell.commandLoop(Shell.java:645)
       ....

**Comment by rainu** [comment]
As an developer you have to configure the "exit" command that will be execute if the user type CTRL-D:

shell.disableExitCommand("exit");
shellBuilder.disableExitCommand("exit");
